typography_spectrum: 0.9533518573734909
color:
  saturation: 0.5531044681556523
  brandStrength: 0.608995164046064
  rhythmicContrast: 0.46638616593554616
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  lightness: 0.2283696411177516
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5943991255480796
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Colton Haas
  email: coltonmhaas@gmail.com
name: Colton Haas
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About
    id: a9d5103e-8adc-4326-be5d-3e72d961ab79
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Colton Haas
description: read my stuff
purpose: []
